project:
  type: website
  output-dir: docs

website:
  title: "kenmelam.github.io"
  navbar:
    left:
      - href: index.qmd
        text: Analysis
      - about.qmd
    

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

